FROM node:23-slim

WORKDIR /app

# Copy only what's needed
COPY package*.json ./
COPY tsconfig.json ./
COPY eFakturaMockServer.ts ./
COPY start.ts ./

RUN npm install

EXPOSE 3005

CMD ["npx", "ts-node", "start.ts"]
