FROM node:18-alpine

WORKDIR /app

# Copy only what's needed
COPY package*.json ./
COPY tsconfig.json ./
COPY eFakturaMockServer.ts ./
COPY start.ts ./

RUN npm install

EXPOSE 3001

CMD ["npx", "ts-node", "start.ts"]
