FROM node:20-slim

# Install dependencies needed for solidity install script
RUN apt-get update && apt-get install -y curl --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy and install deps
COPY package*.json ./
RUN npm install

# Copy rest of the project
COPY . .

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8545

CMD ["/entrypoint.sh"]
