version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  nestjs:
    build: .
    restart: always
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
